# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['@all']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kauth': '@latest-kf6'
    'frameworks/kcodecs': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kconfigwidgets': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kdbusaddons': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kpackage': '@latest-kf6'
    'frameworks/kservice': '@latest-kf6'
    'frameworks/ksvg': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/kcmutils': '@latest-kf6'
    'frameworks/kirigami': '@latest-kf6'
    'plasma/libplasma': '@same'
    'plasma/libkscreen': '@same'
    'plasma/layer-shell-qt': '@same'

RuntimeDependencies:
 - 'on': ['@all']
   'require':
    'frameworks/kimageformats': '@latest-kf6'

Options:
 json-validate-ignore: ['tests/kded/serializerdata/corruptConfig.json']
 run-qmllint: true
