# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kauth': '@latest'
    'frameworks/kcodecs': '@latest'
    'frameworks/kconfig': '@latest'
    'frameworks/kconfigwidgets': '@latest'
    'frameworks/kcoreaddons': '@latest'
    'frameworks/kdbusaddons': '@latest'
    'frameworks/kdeclarative': '@latest'
    'frameworks/kglobalaccel': '@latest'
    'frameworks/ki18n': '@latest'
    'frameworks/kpackage': '@latest'
    'frameworks/kservice': '@latest'
    'frameworks/kwidgetsaddons': '@latest'
    'frameworks/kwindowsystem': '@latest'
    'frameworks/kxmlgui': '@latest'
    'frameworks/kcmutils': '@latest'
    'plasma/plasma-framework': 'kf5'
    'plasma/libkscreen': '@same'
    'plasma/layer-shell-qt': '@same'
