[Desktop Entry]
Name=KScreen 2
Name[ca]=KScreen 2
Name[cs]=KScreen 2
Name[de]=KScreen 2
Name[es]=KScreen 2
Name[fi]=KScreen 2
Name[fr]=KScreen 2
Name[nb]=KScreen 2
Name[nl]=KScreen 2
Name[pl]=KEkran 2
Name[pt]=KScreen 2
Name[pt_BR]=KScreen 2
Name[sk]=KScreen 2
Name[sv]=Kscreen 2
Name[uk]=KScreen 2
Name[x-test]=xxKScreen 2xx
Name[zh_CN]=KScreen 2
Comment=Screen management
Comment[ca]=Gestió de pantalla
Comment[cs]=Správa obrazovek
Comment[de]=Bildschirm-Verwaltung
Comment[es]=Gestión de la pantalla
Comment[fi]=Näyttöjen hallinta
Comment[fr]=Gestion d'écrans
Comment[nb]=Skjembehandling
Comment[nl]=Schermbeheer
Comment[pl]=Zarządzanie ekranem
Comment[pt]=Gestão do ecrã
Comment[pt_BR]=Gerenciamento de telas
Comment[sk]=Správa obrazoviek
Comment[sv]=Skärmhantering
Comment[uk]=Керування екраном
Comment[x-test]=xxScreen managementxx
Comment[zh_CN]=屏幕管理

Type=Service
Icon=preferences-system-power-management
X-KDE-ServiceTypes=KDEDModule
X-KDE-Library=kscreen
X-KDE-DBus-ModuleName=kscreen
X-KDE-Kded-autoload=true
X-KDE-Kded-load-on-demand=false
X-KDE-Kded-phase=1
X-KDE-PluginInfo-Version=@KSCREEN_VERSION@
