[Desktop Entry]
Name=KScreen 2
Name[ar]=شاشتك 2
Name[bs]=KScreen 2
Name[ca]=KScreen 2
Name[ca@valencia]=KScreen 2
Name[cs]=KScreen 2
Name[da]=KScreen 2
Name[de]=KScreen 2
Name[el]=KScreen 2
Name[en_GB]=KScreen 2
Name[es]=KScreen 2
Name[et]=KScreen 2
Name[eu]=KScreen 2
Name[fi]=KScreen 2
Name[fr]=KScreen 2
Name[gl]=KScreen 2
Name[he]=KScreen 2
Name[hu]=KScreen 2
Name[ia]=Kscreen 2
Name[id]=KScreen 2
Name[it]=KScreen 2
Name[ja]=KScreen 2
Name[ko]=KScreen 2
Name[lt]=KScreen 2
Name[lv]=KScreen 2
Name[ml]=കെസ്ക്രീൻ 2
Name[nb]=KScreen 2
Name[nl]=KScreen 2
Name[nn]=KScreen 2
Name[pa]=KScreen 2
Name[pl]=KEkran 2
Name[pt]=KScreen 2
Name[pt_BR]=KScreen 2
Name[ro]=KScreen 2
Name[ru]=KScreen 2
Name[sk]=KScreen 2
Name[sl]=KScreen 2
Name[sr]=К‑екран 2
Name[sr@ijekavian]=К‑екран 2
Name[sr@ijekavianlatin]=K‑ekran 2
Name[sr@latin]=K‑ekran 2
Name[sv]=Kscreen 2
Name[tg]=KScreen 2
Name[tr]=KScreen 2
Name[uk]=KScreen 2
Name[x-test]=xxKScreen 2xx
Name[zh_CN]=KScreen 2
Name[zh_TW]=KScreen 2
Comment=Screen management
Comment[ar]=إدارة الشّاشة
Comment[bs]=Upravljanje ekranom
Comment[ca]=Gestió de la pantalla
Comment[ca@valencia]=Gestió de la pantalla
Comment[cs]=Správa obrazovek
Comment[da]=Håndtering af skærme
Comment[de]=Bildschirm-Verwaltung
Comment[el]=Διαχείριση οθόνης
Comment[en_GB]=Screen management
Comment[es]=Gestión de la pantalla
Comment[et]=Ekraanihaldur
Comment[eu]=Pantaila kudeatzailea
Comment[fi]=Näyttöjen hallinta
Comment[fr]=Gestion d'écrans
Comment[gl]=Xestor de pantalla
Comment[he]=ניהול מסכים
Comment[hu]=Képernyőkezelés
Comment[ia]=Gestion de schermo
Comment[id]=Pengelolaan layar
Comment[it]=Gestione dello schermo
Comment[ja]=ディスプレイの管理
Comment[ko]=화면 관리
Comment[lt]=Ekrano tvarkymas
Comment[lv]=Ekrānu pārvaldība
Comment[ml]=സ്ക്രീൻ നടത്തിപ്പ്
Comment[nb]=Skjembehandling
Comment[nl]=Schermbeheer
Comment[nn]=Skjermhandsaming
Comment[pa]=ਸਕਰੀਨ ਪਰਬੰਧ
Comment[pl]=Zarządzanie ekranem
Comment[pt]=Gestão do ecrã
Comment[pt_BR]=Gerenciamento de telas
Comment[ro]=Gestiunea ecranelor
Comment[ru]=Управление экранами
Comment[sk]=Správa obrazoviek
Comment[sl]=Upravljanje zaslonov
Comment[sr]=Управљање екраном
Comment[sr@ijekavian]=Управљање екраном
Comment[sr@ijekavianlatin]=Upravljanje ekranom
Comment[sr@latin]=Upravljanje ekranom
Comment[sv]=Skärmhantering
Comment[tg]=Идоракунии экран
Comment[tr]=Ekran yönetimi
Comment[uk]=Керування екраном
Comment[x-test]=xxScreen managementxx
Comment[zh_CN]=屏幕管理
Comment[zh_TW]=螢幕管理

Type=Service
Icon=preferences-system-power-management
X-KDE-ServiceTypes=KDEDModule
X-KDE-Library=kscreen
X-KDE-Kded-autoload=true
X-KDE-Kded-load-on-demand=false
X-KDE-Kded-phase=1
X-KDE-PluginInfo-Version=@KSCREEN_VERSION@
