[Desktop Entry]
Exec=kcmshell5 kcm_kscreen
Icon=preferences-desktop-display-randr
Type=Service
X-KDE-ServiceTypes=KCModule
X-KDE-Library=kcm_kscreen
X-KDE-ParentApp=kcontrol
X-KDE-System-Settings-Parent-Category=display
X-KDE-Weight=40
X-KDE-PluginInfo-Version=@KSCREEN_VERSION@

Name=Display Configuration
Name[ar]=اضبط العرض
Name[bs]=Konfiguracija ekrana
Name[ca]=Configuració de la pantalla
Name[cs]=Nastavení zobrazení
Name[de]=Anzeige-Einrichtung
Name[el]=Διαμόρφωση οθόνης
Name[en_GB]=Display Configuration
Name[es]=Configuración de la pantalla
Name[fi]=Näyttöasetukset
Name[fr]=Configuration de l'affichage
Name[gl]=Configuración da pantalla
Name[hu]=Kijelzőbeállítás
Name[it]=Configurazione dello schermo
Name[nb]=Skjermoppsett
Name[nl]=Instellingen van het scherm
Name[pa]=ਡਿਸਪਲੇਅ ਸੰਰਚਨਾ
Name[pl]=Ustawienia wyświetlacza
Name[pt]=Configuração do Ecrã
Name[pt_BR]=Configuração da tela
Name[sk]=Nastavenie obrazovky
Name[sl]=Nastavitve zaslona
Name[sr]=Подешавање екрана
Name[sr@ijekavian]=Подешавање екрана
Name[sr@ijekavianlatin]=Podešavanje ekrana
Name[sr@latin]=Podešavanje ekrana
Name[sv]=Inställning av bildskärm
Name[tr]=Ekran Yapılandırması
Name[uk]=Налаштування дисплея
Name[x-test]=xxDisplay Configurationxx
Name[zh_CN]=显示配置
Name[zh_TW]=顯示設定
Comment=Manage and configure monitors and displays
Comment[ar]=أدر واضبط الشّاشات والعروض
Comment[bs]=Upravljanje i konfiguracija monitora i ekrana
Comment[ca]=Gestiona i configura els monitors i pantalles
Comment[cs]=Spravovat a nastavit monitory a zobrazení
Comment[de]=Verwaltung und Einrichtung vom Monitoren und Anzeigen
Comment[el]=Διαχείριση και διαμόρφωση οθονών και απεικονίσεων
Comment[en_GB]=Manage and configure monitors and displays
Comment[es]=Gestionar y configurar monitores y pantallas
Comment[fi]=Näyttöjen asetusten hallinta
Comment[fr]=Gère et configure les moniteurs et les écrans
Comment[gl]=Xestiona a configura os monitores e a resolución
Comment[hu]=Monitorok és kijelzők kezelése és beállítása
Comment[it]=Gestisci e configura monitor e schermi
Comment[nb]=Håndter og sett opp monitorer og skjermer
Comment[nl]=Monitoren en schermen beheren en instellen
Comment[pa]=ਮਾਨੀਟਰ ਤੇ ਡਿਸਪਲੇਅ ਦਾ ਪਰਬੰਧ ਤੇ ਸੰਰਚਨਾ ਕਰੋ
Comment[pl]=Zarządzanie i ustawienia monitorów i wyświetlaczy
Comment[pt]=Faz a gestão e configuração dos monitores e ecrãs
Comment[pt_BR]=Gerencia e configura monitores e telas
Comment[sk]=Správa a nastavenie monitorov a obrazoviek
Comment[sl]=Upravljajte in nastavljajte zaslone in prikazovalnike
Comment[sr]=Управљање и подешавање монитора̂ и екрана̂
Comment[sr@ijekavian]=Управљање и подешавање монитора̂ и екрана̂
Comment[sr@ijekavianlatin]=Upravljanje i podešavanje monitorâ̂ i ekranâ̂
Comment[sr@latin]=Upravljanje i podešavanje monitorâ̂ i ekranâ̂
Comment[sv]=Hantera och ställ in bildskärmar
Comment[tr]=Ekranları ve görüntüleri yönet, yapılandır
Comment[uk]=Керування і налаштовування моніторів і дисплеїв
Comment[x-test]=xxManage and configure monitors and displaysxx
Comment[zh_CN]=管理和配置显示和监视器
Comment[zh_TW]=管理與設定螢幕與顯示
