[Desktop Entry]
Name=Quick Display Configuration
Name[ar]=ضبط سريع للعرض
Name[ast]=Configuración rápida de pantalla
Name[bs]=Brza konfiguracija ekrana
Name[ca]=Configuració ràpida de la pantalla
Name[cs]=Rychlé nastavení zobrazení
Name[de]=Schnelle Anzeige-Einrichtung
Name[el]=Γρήγορη διαμόρφωση οθόνης
Name[en_GB]=Quick Display Configuration
Name[es]=Configuración rápida de la pantalla
Name[fi]=Näyttöasetusten pikasäätö
Name[fr]=Configuration rapide de l'affichage
Name[gl]=Configuración rápida da pantalla
Name[hu]=Gyors megjelenítő-beállítás
Name[it]=Configurazione rapida dello schermo
Name[ko]=빠른 화면 설정
Name[lt]=Greita ekrano konfigūracija
Name[nb]=Hurtig skjermoppsett
Name[nl]=Snel instellen van scherm
Name[pa]=ਤੁਰੰਤ ਡਿਸਪਲੇਅ ਸੰਰਚਨਾ
Name[pl]=Szybkie ustawienia wyświetlacza
Name[pt]=Configuração Rápida do Ecrã
Name[pt_BR]=Configuração rápida da tela
Name[ro]=Configurare rapidă afișaj
Name[ru]=Быстрая настройка экрана
Name[sk]=Rýchle nastavenie obrazovky
Name[sl]=Hitre nastavitve zaslona
Name[sr]=Брзо подешавање екрана
Name[sr@ijekavian]=Брзо подешавање екрана
Name[sr@ijekavianlatin]=Brzo podešavanje ekrana
Name[sr@latin]=Brzo podešavanje ekrana
Name[sv]=Snabbinställning av skärm
Name[tr]=Hızlı Ekran Yapılandırması
Name[uk]=Швидке налаштовування дисплея
Name[x-test]=xxQuick Display Configurationxx
Name[zh_CN]=快捷显示管理
Name[zh_TW]=快速顯示設定
Comment=Quick configuration of a new display
Comment[ar]=ضبط سريع لعرض جديد
Comment[ast]=Configuración rápida d'una pantalla nueva
Comment[bs]=Brza konfiguracija novog ekrana
Comment[ca]=Configuració ràpida d'una nova pantalla
Comment[cs]=Rychlé nastavení nového zobrazení
Comment[de]=Schnelle Einrichtung einer neuen Anzeige
Comment[el]=Γρήγορη διαμόρφωση μιας νέας οθόνης
Comment[en_GB]=Quick configuration of a new display
Comment[es]=Configuración rápida de una nueva pantalla
Comment[fi]=Näyttöasetusten pikasäätö
Comment[fr]=Configuration rapide d'un nouvel affichage
Comment[gl]=Configura rapidamente unha nova pantalla
Comment[hu]=Új megjelenítők gyors beállítása
Comment[it]=Configurazione rapida di un nuovo schermo
Comment[ko]=새 디스플레이 빠른 설정
Comment[lt]=Grupės naujo ekrano konfigūracija
Comment[nb]=Hurtig oppsett av en ny skjerm
Comment[nl]=Snel instellen van een nieuwe scherm
Comment[pa]=ਨਵੇਂ ਡਿਸਪਲੇਅ ਲਈ ਤੁਰੰਤ ਸੰਰਚਨਾ
Comment[pl]=Szybkie ustawienia nowego wyświetlacza
Comment[pt]=Configuração rápida de um novo ecrã
Comment[pt_BR]=Configuração rápida de uma nova tela
Comment[ro]=Configurare rapidă a unui nou afișaj
Comment[ru]=Быстрая настройка нового экрана
Comment[sk]=Rýchle nastavenie novej obrazovky
Comment[sl]=Hitre nastavitve novega zaslona
Comment[sr]=Брзо подешавање за нов екран
Comment[sr@ijekavian]=Брзо подешавање за нов екран
Comment[sr@ijekavianlatin]=Brzo podešavanje za nov ekran
Comment[sr@latin]=Brzo podešavanje za nov ekran
Comment[sv]=Snabbinställning av en ny skärm
Comment[tr]=Yeni bir ekranın hızlı yapılandırması
Comment[uk]=Швидке налаштовування нового дисплея
Comment[x-test]=xxQuick configuration of a new displayxx
Comment[zh_CN]=快捷配置新显示器
Comment[zh_TW]=快速設定新的顯示

Icon=preferences-desktop-display-randr
Type=Service
X-KDE-ServiceTypes=Plasma/Applet,Plasma/PopupApplet

X-Plasma-DefaultSize=290,150
X-Plasma-NotificationArea=true
X-Plasma-ConfigPlugins=kscreen

X-KDE-Library=plasma_applet_kscreen
X-KDE-PluginInfo-Author=Dan Vrátil
X-KDE-PluginInfo-Email=dvratil@redhat.com
X-KDE-PluginInfo-Name=org.kde.plasma.kscreen
X-KDE-PluginInfo-Version=@KSCREEN_VERSION@
X-KDE-PluginInfo-Website=http://www.kde.org
X-KDE-PluginInfo-Category=System Information
X-KDE-PluginInfo-Depends=
X-KDE-PluginInfo-License=GPL
X-KDE-PluginInfo-EnabledByDefault=true
